### ISSUE TITLE
Support for PHP8

### ISSUE THREAD

**Issue by visto9259** [LM-Commons/LmcRbac#11]
Review code to remove any deprecations from PHP8

**Comment by FabianKoestring** [comment]
Are there any known problem spots where anything big must be changed? We are willing to update our php version but the are some blocking vendors left (`https://github.com/LM-Commons/LmcRbac`, `https://github.com/LM-Commons/LmcRbacMvc`).

**Comment by visto9259** [comment]
I have not looked at the code yet. I do not anticipate any issues.  Just lacking time to work on this.

**Comment by visto9259** [comment]
There is a `require-dev` dependency on `doctrine/doctrice-orm-module` which has not been updated to support PHP8.  
`doctrine/doctrice-orm-module` needs to be updated to use `laminas/laminas-cache 3.x`.
There is already an issue raised again `doctrine/doctrice-orm-module` for that.
As soon as that's fixed, I will be able to finalize the support for PHP8.  Right now I can't run the test suite against 8.0

**Comment by FabianKoestring** [comment]
> There is a `require-dev` dependency on `doctrine/doctrice-orm-module` which has not been updated to support PHP8.
> `doctrine/doctrice-orm-module` needs to be updated to use `laminas/laminas-cache 3.x`.
> There is already an issue raised again `doctrine/doctrice-orm-module` for that.
> As soon as that's fixed, I will be able to finalize the support for PHP8. Right now I can't run the test suite against 8.0

👍 Just looked into https://github.com/doctrine/DoctrineORMModule. There is a 4.0.0 Release with PHP 8 Support.

**Comment by visto9259** [comment]
@FabianKoestring Yes but `DoctrineORMModule` depends on `DoctrineModule` which depends on `laminas-cache 2.x`.  Doctrine needs to update this last dependency to `laminas-cache 3.x` which supports PHP8.

Many people have raised issues against `DoctrineModule` on that topic.

The `LmcRbac` code itself supports PHP8 but I want to be able to run the test suite to QA it before release.  I will look into doing a release candidate of `LmcRbac` without QA in the interim.

**Comment by visto9259** [comment]
@FabianKoestring Has it turns out, the dependency on `doctrine/doctrine-orm-module` in the `require-dev` is not required.  Not sure why it was there in the first place.
I will update `composer.json` and release a PHP8 version of the library in the coming days.

**Comment by FabianKoestring** [comment]
> @FabianKoestring Has it turns out, the dependency on `doctrine/doctrine-orm-module` in the `require-dev` is not required. Not sure why it was there in the first place.
> I will update `composer.json` and release a PHP8 version of the library in the coming days.

Great News! Will you make a release for https://github.com/LM-Commons/LmcRbac and https://github.com/LM-Commons/LmcRbacMvc?

**Comment by visto9259** [comment]
>> @FabianKoestring Has it turns out, the dependency on doctrine/doctrine-orm-module in the require-dev is not required. Not sure why it was there in the first place.
I will update composer.json and release a PHP8 version of the library in the coming days.
>
>Great News! Will you make a release for https://github.com/LM-Commons/LmcRbac and https://github.com/LM-Commons/LmcRbacMvc?

Targeting this weekend for `LmcRbac`.  `LmcRbacMvc` will require more work and it will come later depending on bandwidth available to me.
